name: Deploy NGINX Container

on:
  push:
    branches:
      - main
    paths:
      - index.html

jobs:
  deploy-nginx:
    runs-on: bka-label

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build NGINX container with custom index.html
      run: |
        mkdir nginx-content
        cp index.html nginx-content/
        docker stop nginx-container || true
        docker rm nginx-container || true
        docker run -d \
          --name nginx-container \
          -p 8081:80 \
          -v $(pwd)/nginx-content:/usr/share/nginx/html:ro \
          nginx
